#!/bin/bash

# Cloudflare Tunnel Setup Script for VCL2
# This script installs cloudflared and sets up a persistent tunnel

set -e

echo "======================================"
echo "Cloudflare Tunnel Setup for Coffee App"
echo "======================================"
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Configuration
TUNNEL_NAME="coffee-vcl2"
SERVICE_URL="http://localhost:3000"
CLOUDFLARED_DIR="$HOME/.cloudflared"

echo -e "${YELLOW}Step 1: Checking prerequisites...${NC}"

# Check if running on VCL2
if [ ! -d "/home" ]; then
    echo -e "${RED}Warning: This script is designed for Linux systems${NC}"
fi

# Check if sudo is available
if ! command -v sudo &> /dev/null; then
    echo -e "${RED}Error: sudo is required but not available${NC}"
    exit 1
fi

echo -e "${GREEN}✓ Prerequisites checked${NC}"
echo ""

# Step 2: Install cloudflared
echo -e "${YELLOW}Step 2: Installing cloudflared...${NC}"

if command -v cloudflared &> /dev/null; then
    echo -e "${GREEN}✓ cloudflared is already installed${NC}"
    cloudflared --version
else
    echo "Downloading cloudflared..."
    
    # Detect architecture
    ARCH=$(uname -m)
    if [ "$ARCH" = "x86_64" ]; then
        DOWNLOAD_URL="https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64"
    elif [ "$ARCH" = "aarch64" ]; then
        DOWNLOAD_URL="https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-arm64"
    else
        echo -e "${RED}Unsupported architecture: $ARCH${NC}"
        exit 1
    fi
    
    wget -q --show-progress "$DOWNLOAD_URL" -O cloudflared
    chmod +x cloudflared
    sudo mv cloudflared /usr/local/bin/
    
    echo -e "${GREEN}✓ cloudflared installed successfully${NC}"
    cloudflared --version
fi

echo ""

# Step 3: Create .cloudflared directory
echo -e "${YELLOW}Step 3: Setting up configuration directory...${NC}"
mkdir -p "$CLOUDFLARED_DIR"
echo -e "${GREEN}✓ Configuration directory created: $CLOUDFLARED_DIR${NC}"
echo ""

# Step 4: Authentication
echo -e "${YELLOW}Step 4: Authenticating with Cloudflare...${NC}"

if [ -f "$CLOUDFLARED_DIR/cert.pem" ]; then
    echo -e "${GREEN}✓ Already authenticated (cert.pem exists)${NC}"
else
    echo ""
    echo "A browser window will open for you to log in to Cloudflare."
    echo "If you're on a remote server, you may need to:"
    echo "  1. Copy the URL that appears"
    echo "  2. Open it in your local browser"
    echo "  3. Complete the authentication"
    echo ""
    read -p "Press Enter to continue with authentication..."

    cloudflared tunnel login

    if [ ! -f "$CLOUDFLARED_DIR/cert.pem" ]; then
        echo -e "${RED}Error: Authentication failed. cert.pem not found.${NC}"
        exit 1
    fi

    echo -e "${GREEN}✓ Authentication successful${NC}"
fi
echo ""

# Step 5: Create tunnel
echo -e "${YELLOW}Step 5: Creating tunnel '$TUNNEL_NAME'...${NC}"

# Check if tunnel already exists
if cloudflared tunnel list | grep -q "$TUNNEL_NAME"; then
    TUNNEL_ID=$(cloudflared tunnel list | grep "$TUNNEL_NAME" | awk '{print $1}')
    
    # Check if credentials file exists
    if [ ! -f "$CLOUDFLARED_DIR/$TUNNEL_ID.json" ]; then
        echo -e "${YELLOW}Tunnel exists but credentials missing. Deleting and recreating...${NC}"
        cloudflared tunnel delete -f "$TUNNEL_ID" 2>/dev/null || true
        cloudflared tunnel create "$TUNNEL_NAME"
        TUNNEL_ID=$(cloudflared tunnel list | grep "$TUNNEL_NAME" | awk '{print $1}')
        echo -e "${GREEN}✓ Tunnel recreated with ID: $TUNNEL_ID${NC}"
    else
        echo -e "${YELLOW}Tunnel '$TUNNEL_NAME' already exists with valid credentials.${NC}"
        echo -e "${GREEN}✓ Using existing tunnel ID: $TUNNEL_ID${NC}"
    fi
else
    cloudflared tunnel create "$TUNNEL_NAME"
    TUNNEL_ID=$(cloudflared tunnel list | grep "$TUNNEL_NAME" | awk '{print $1}')
    echo -e "${GREEN}✓ Tunnel created with ID: $TUNNEL_ID${NC}"
fi

echo ""

# Step 6: Create configuration file
echo -e "${YELLOW}Step 6: Creating tunnel configuration...${NC}"

CONFIG_FILE="$CLOUDFLARED_DIR/config.yml"

cat > "$CONFIG_FILE" << EOF
tunnel: $TUNNEL_ID
credentials-file: $CLOUDFLARED_DIR/$TUNNEL_ID.json

ingress:
  # Route all traffic to the coffee app
  - service: $SERVICE_URL
    originRequest:
      noTLSVerify: true

# Logging (optional, uncomment if needed)
# loglevel: info
# logfile: /var/log/cloudflared.log
EOF

echo -e "${GREEN}✓ Configuration file created: $CONFIG_FILE${NC}"
echo ""

# Step 7: Get tunnel URL
echo -e "${YELLOW}Step 7: Getting tunnel information...${NC}"
echo ""
echo "Tunnel Details:"
echo "  Name: $TUNNEL_NAME"
echo "  ID: $TUNNEL_ID"
echo "  Service: $SERVICE_URL"
echo ""

# The tunnel URL is generated by Cloudflare, we'll see it when we run the tunnel
echo -e "${YELLOW}Note: The public URL will be displayed when you start the tunnel.${NC}"
echo ""

# Step 8: Test tunnel
echo -e "${YELLOW}Step 8: Testing tunnel (this will run for 10 seconds)...${NC}"
echo "Starting tunnel..."
echo ""

# Run tunnel in background for testing
cloudflared tunnel --config "$CONFIG_FILE" run "$TUNNEL_NAME" &
TUNNEL_PID=$!

sleep 10

# Check if tunnel is still running
if ps -p $TUNNEL_PID > /dev/null; then
    echo -e "${GREEN}✓ Tunnel is running successfully!${NC}"
    kill $TUNNEL_PID
    wait $TUNNEL_PID 2>/dev/null || true
else
    echo -e "${RED}Error: Tunnel failed to start${NC}"
    exit 1
fi

echo ""

# Step 9: Install systemd service
echo -e "${YELLOW}Step 9: Installing systemd service for auto-start...${NC}"

# Uninstall existing service if any (ignore errors)
sudo cloudflared service uninstall 2>/dev/null || true

# Install with explicit config path
sudo cloudflared --config "$CONFIG_FILE" service install

echo -e "${GREEN}✓ Systemd service installed${NC}"
echo ""

# Step 10: Enable and start service
echo -e "${YELLOW}Step 10: Enabling and starting cloudflared service...${NC}"

sudo systemctl daemon-reload
sudo systemctl enable cloudflared
sudo systemctl restart cloudflared

sleep 3

# Check service status
if sudo systemctl is-active --quiet cloudflared; then
    echo -e "${GREEN}✓ Cloudflared service is running!${NC}"
else
    echo -e "${RED}Warning: Service may not be running. Check with: sudo systemctl status cloudflared${NC}"
fi

echo ""
echo "======================================"
echo -e "${GREEN}Installation Complete!${NC}"
echo "======================================"
echo ""
echo "Next Steps:"
echo "  1. Get your tunnel URL:"
echo "     cloudflared tunnel info $TUNNEL_NAME"
echo ""
echo "  2. Check service status:"
echo "     sudo systemctl status cloudflared"
echo ""
echo "  3. View logs:"
echo "     sudo journalctl -u cloudflared -f"
echo ""
echo "  4. Your public URL will be shown in the logs above"
echo "     Look for: https://...trycloudflare.com"
echo ""
echo "  5. To get the URL anytime:"
echo "     sudo journalctl -u cloudflared | grep trycloudflare.com"
echo ""
echo "Useful Commands:"
echo "  - Stop tunnel:    sudo systemctl stop cloudflared"
echo "  - Start tunnel:   sudo systemctl start cloudflared"
echo "  - Restart tunnel: sudo systemctl restart cloudflared"
echo "  - View logs:      sudo journalctl -u cloudflared -f"
echo ""

